#!/bin/bash
# setup.sh - Setup instructions for PostgreSQL elog prototype
#
# This script provides instructions for setting up the PostgreSQL
# database with Row-Level Security for elog-copilot.

set -e

echo "=============================================="
echo "PostgreSQL Elog Prototype Setup"
echo "=============================================="
echo ""
echo "PREREQUISITES:"
echo "  1. PostgreSQL server (12+) with superuser access"
echo "  2. Access to centralized elog SQLite database"
echo ""
echo "STEPS:"
echo ""
echo "1. Create database and user:"
echo "   --------------------------"
echo "   createdb elog_prototype"
echo "   createuser elog_user"
echo ""
echo "2. Load schema:"
echo "   -------------"
echo "   psql -d elog_prototype -f sql/01_schema.sql"
echo ""
echo "3. Enable RLS policies:"
echo "   ---------------------"
echo "   psql -d elog_prototype -f sql/02_rls_policies.sql"
echo ""
echo "4. Load test data:"
echo "   ----------------"
echo "   psql -d elog_prototype -f sql/03_test_data.sql"
echo ""
echo "5. Create database users for testing:"
echo "   -----------------------------------"
echo "   psql -d elog_prototype -c \"CREATE USER staff_user;\""
echo "   psql -d elog_prototype -c \"CREATE USER pi_user;\""
echo "   psql -d elog_prototype -c \"CREATE USER collab_user;\""
echo "   psql -d elog_prototype -c \"GRANT SELECT ON ALL TABLES IN SCHEMA public TO staff_user, pi_user, collab_user;\""
echo ""
echo "6. Test RLS:"
echo "   ---------"
echo "   # As staff_user (sees 4 experiments):"
echo "   psql -d elog_prototype -U staff_user -c \"SELECT experiment_id FROM experiments;\""
echo ""
echo "   # As pi_user (sees 1 experiment):"
echo "   psql -d elog_prototype -U pi_user -c \"SELECT experiment_id FROM experiments;\""
echo ""
echo "   # As collab_user (sees 2 experiments):"
echo "   psql -d elog_prototype -U collab_user -c \"SELECT experiment_id FROM experiments;\""
echo ""
echo "=============================================="
echo ""
echo "OPEN QUESTIONS (see docs/postgres-rls-design.md):"
echo "  - PostgreSQL hosting: Use existing LCLS Postgres or new instance?"
echo "  - User authentication: Unix socket peer auth vs password vs Kerberos?"
echo "  - Permission sync: How to sync Unix groups to user_experiment_access?"
echo "  - Data sync: Keep Postgres in sync with authoritative elog source?"
echo ""
echo "=============================================="
