#!/bin/bash
# setup_postgres.sh - Install and start a self-contained PostgreSQL 16 server
#
# Uses micromamba to install PostgreSQL into a local environment.
# All directories (pg_env, pg_data, pg_logs) are local to this repo.
#
# Usage:
#   bash scripts/setup_postgres.sh          # Full setup (install + init + start)
#   bash scripts/setup_postgres.sh start    # Start existing server
#   bash scripts/setup_postgres.sh stop     # Stop server
#   bash scripts/setup_postgres.sh status   # Check server status

set -euo pipefail

# Paths (all relative to repo root)
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PG_ENV="$REPO_DIR/pg_env"
PG_DATA="$REPO_DIR/pg_data"
PG_LOGS="$REPO_DIR/pg_logs"
PG_PORT=5434
DB_NAME="elog_prototype"
PG_TOOLS="$REPO_DIR/pg_tools"
MICROMAMBA_BIN="$PG_TOOLS/micromamba"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# --------------------------------------------------------------------------
# Command handlers
# --------------------------------------------------------------------------

cmd_stop() {
    if [ -f "$PG_DATA/postmaster.pid" ]; then
        info "Stopping PostgreSQL..."
        "$PG_ENV/bin/pg_ctl" -D "$PG_DATA" -l "$PG_LOGS/postgresql.log" stop
        info "PostgreSQL stopped."
    else
        warn "PostgreSQL is not running (no postmaster.pid found)."
    fi
}

cmd_start() {
    if [ -f "$PG_DATA/postmaster.pid" ]; then
        warn "PostgreSQL appears to be already running."
        "$PG_ENV/bin/pg_ctl" -D "$PG_DATA" status || true
        return
    fi
    info "Starting PostgreSQL on port $PG_PORT..."
    "$PG_ENV/bin/pg_ctl" -D "$PG_DATA" -l "$PG_LOGS/postgresql.log" -o "-p $PG_PORT" start
    info "PostgreSQL started on port $PG_PORT."
}

cmd_status() {
    if [ -d "$PG_DATA" ]; then
        "$PG_ENV/bin/pg_ctl" -D "$PG_DATA" status || true
    else
        warn "PG_DATA directory does not exist. Run setup first."
    fi
}

# Handle subcommands
case "${1:-setup}" in
    stop)   cmd_stop; exit 0 ;;
    start)  cmd_start; exit 0 ;;
    status) cmd_status; exit 0 ;;
    setup)  ;; # Fall through to full setup below
    *)      error "Unknown command: $1. Use setup|start|stop|status" ;;
esac

# ==========================================================================
# Full setup
# ==========================================================================

info "Setting up PostgreSQL for elog-copilot prototype"
info "  Repo:    $REPO_DIR"
info "  PG env:  $PG_ENV"
info "  PG data: $PG_DATA"
info "  Port:    $PG_PORT"
echo ""

# --------------------------------------------------------------------------
# Step 1: Install micromamba (if needed)
# --------------------------------------------------------------------------

if [ ! -x "$MICROMAMBA_BIN" ]; then
    info "Installing micromamba into $PG_TOOLS..."
    mkdir -p "$PG_TOOLS"
    curl -fsSL https://micro.mamba.pm/api/micromamba/linux-64/latest \
        | tar -xvj -C "$PG_TOOLS" --strip-components=1 bin/micromamba
    info "micromamba installed."
else
    info "micromamba already installed."
fi

# --------------------------------------------------------------------------
# Step 2: Install PostgreSQL 16 via micromamba
# --------------------------------------------------------------------------

if [ ! -x "$PG_ENV/bin/pg_ctl" ]; then
    info "Installing PostgreSQL 16 via micromamba..."
    # Use a cache dir with available space (scratch may be full)
    export MAMBA_ROOT_PREFIX="$PG_TOOLS/mamba_root"
    export CONDA_PKGS_DIRS="$PG_TOOLS/mamba_root/pkgs"
    mkdir -p "$MAMBA_ROOT_PREFIX" "$CONDA_PKGS_DIRS"
    "$MICROMAMBA_BIN" create -p "$PG_ENV" -c conda-forge postgresql=16 -y
    info "PostgreSQL 16 installed."
else
    info "PostgreSQL already installed."
fi

# Verify pg_ctl is available
"$PG_ENV/bin/pg_ctl" --version || error "pg_ctl not found after install"

# --------------------------------------------------------------------------
# Step 3: Initialize database cluster
# --------------------------------------------------------------------------

if [ ! -f "$PG_DATA/PG_VERSION" ]; then
    info "Initializing database cluster..."
    mkdir -p "$PG_DATA" "$PG_LOGS"
    "$PG_ENV/bin/initdb" -D "$PG_DATA" --auth=trust --encoding=UTF8 --locale=C
    info "Database cluster initialized."
else
    info "Database cluster already exists."
fi

# --------------------------------------------------------------------------
# Step 4: Configure PostgreSQL
# --------------------------------------------------------------------------

info "Configuring PostgreSQL..."

# postgresql.conf: set port, listen only on localhost
cat > "$PG_DATA/postgresql.conf" <<PGCONF
# Generated by setup_postgres.sh
port = $PG_PORT
listen_addresses = 'localhost'
max_connections = 20
shared_buffers = 256MB
work_mem = 64MB
maintenance_work_mem = 256MB
effective_cache_size = 512MB

# Logging
logging_collector = on
log_directory = '$PG_LOGS'
log_filename = 'postgresql-%Y-%m-%d.log'
log_statement = 'ddl'

# Unix socket in /tmp (default for micromamba PG)
unix_socket_directories = '/tmp'

# WAL settings (relaxed for dev prototype)
wal_level = minimal
max_wal_senders = 0
fsync = off
synchronous_commit = off
PGCONF

# pg_hba.conf: trust auth for local connections
cat > "$PG_DATA/pg_hba.conf" <<HBA
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# Unix socket connections (trust for dev)
local   all             all                                     trust
# IPv4 local connections
host    all             all             127.0.0.1/32            trust
# IPv6 local connections
host    all             all             ::1/128                 trust
HBA

info "Configuration written."

# --------------------------------------------------------------------------
# Step 5: Start the server
# --------------------------------------------------------------------------

if [ -f "$PG_DATA/postmaster.pid" ]; then
    warn "PostgreSQL appears to be already running. Restarting..."
    "$PG_ENV/bin/pg_ctl" -D "$PG_DATA" -l "$PG_LOGS/postgresql.log" restart
else
    info "Starting PostgreSQL..."
    "$PG_ENV/bin/pg_ctl" -D "$PG_DATA" -l "$PG_LOGS/postgresql.log" -o "-p $PG_PORT" start
fi

# Wait for server to be ready
info "Waiting for server to be ready..."
for i in $(seq 1 30); do
    if "$PG_ENV/bin/pg_isready" -p "$PG_PORT" -h /tmp >/dev/null 2>&1; then
        break
    fi
    sleep 1
done

"$PG_ENV/bin/pg_isready" -p "$PG_PORT" -h /tmp || error "Server did not start within 30 seconds"
info "PostgreSQL is ready."

# --------------------------------------------------------------------------
# Step 6: Create database
# --------------------------------------------------------------------------

if "$PG_ENV/bin/psql" -h /tmp -p "$PG_PORT" -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
    info "Database '$DB_NAME' already exists."
else
    info "Creating database '$DB_NAME'..."
    "$PG_ENV/bin/createdb" -h /tmp -p "$PG_PORT" "$DB_NAME"
    info "Database created."
fi

# --------------------------------------------------------------------------
# Done
# --------------------------------------------------------------------------

echo ""
info "========================================="
info "PostgreSQL setup complete!"
info "========================================="
info ""
info "Connection info:"
info "  Host:     /tmp (unix socket)"
info "  Port:     $PG_PORT"
info "  Database: $DB_NAME"
info "  Auth:     trust (no password needed)"
info ""
info "Quick connect:"
info "  $PG_ENV/bin/psql -h /tmp -p $PG_PORT -d $DB_NAME"
info ""
info "Next steps:"
info "  1. Load schema:     $PG_ENV/bin/psql -h /tmp -p $PG_PORT -d $DB_NAME -f sql/01_schema.sql"
info "  2. Enable RLS:      $PG_ENV/bin/psql -h /tmp -p $PG_PORT -d $DB_NAME -f sql/02_rls_policies.sql"
info "  3. Migrate data:    UV_CACHE_DIR=/sdf/data/lcls/ds/prj/prjdat21/results/cwang31/.UV_CACHE uv run --with psycopg2-binary scripts/migrate_sqlite_to_postgres.py"
info "  4. Create users:    $PG_ENV/bin/psql -h /tmp -p $PG_PORT -d $DB_NAME -f sql/04_test_users.sql"
info "  5. Verify RLS:      bash scripts/verify_rls.sh"
info ""
info "Server management:"
info "  bash scripts/setup_postgres.sh stop"
info "  bash scripts/setup_postgres.sh start"
info "  bash scripts/setup_postgres.sh status"
